version: '3.8'
services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: ./infra/Dockerfile.n8n
    ports:
      - '5678:5678'
    environment: &n8n_env
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-Gk9a3XvYnGk9a3XvYnGk9a3XvYnGk9a3XvYnGk9a3XvYnGk9a3XvYnGk9a3X}
      - EXECUTIONS_MODE=${EXECUTIONS_MODE:-queue}
      # - DB_TYPE=${DB_TYPE:-mysqldb}
      # - DB_MYSQLDB_DATABASE=${DB_MYSQLDB_DATABASE:-n8n}
      # - DB_MYSQLDB_HOST=${DB_MYSQLDB_HOST:-n8n_mysql}
      # - DB_MYSQLDB_PORT=${DB_MYSQLDB_PORT:-3306}
      # - DB_MYSQLDB_USER=${DB_MYSQLDB_USER:-n8n_user}
      # - DB_MYSQLDB_PASSWORD=${DB_MYSQLDB_PASSWORD:-n8n_password}
      - DB_TYPE=${DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE:-n8n}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST:-n8n_postgres}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT:-5432}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER:-n8n_user}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD:-n8n_password}
      - QUEUE_BULL_REDIS_HOST=${QUEUE_BULL_REDIS_HOST:-n8n_redis}
      - QUEUE_BULL_REDIS_PORT=${QUEUE_BULL_REDIS_PORT:-6379}
      - CONCURRENCY=${CONCURRENCY:-12}
    # volumes:
    #   - ./n8n:/root/.n8n
    restart: unless-stopped
    depends_on:
      - n8n_postgres
      - n8n_redis
    extra_hosts:
      - 'dockernet:host-gateway'
      - 'newway:host-gateway'
    healthcheck:
      test: curl --fail http://localhost:5678 || exit 1
      interval: 8s
      timeout: 10s
      retries: 6
    deploy:
      resources: &n8n_resources
        limits:
          memory: 1G
          cpus: "0.23"
  n8n_workers:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.n8n_worker
    environment: *n8n_env
    restart: unless-stopped
    # command: n8n worker --concurrency=${CONCURRENCY:-8}
    deploy:
      replicas: '${N8N_WORKERS_REPLICAS:-3}'
      resources: *n8n_resources
    depends_on:
      n8n:
        condition: service_healthy
    extra_hosts:
      - 'dockernet:host-gateway'
      - 'newway:host-gateway'
  # n8n_mysql:
  #   container_name: n8n_mysql
  #   image: mysql:5.7
  #   ports:
  #     - '3307:3306'
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE:-n8n}
  #     - MYSQL_USER=${MYSQL_DATABASE:-n8n_user}
  #     - MYSQL_PASSWORD=${MYSQL_DATABASE:-n8n_password}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_DATABASE:-n8n_password}
  #   volumes:
  #     - ./data/db/mysql:/var/lib/mysql
  #   extra_hosts:
  #     - 'dockernet:host-gateway'
  #     - 'newway:host-gateway'
  n8n_postgres:
    container_name: n8n_postgres
    image: postgres:15.3-alpine3.18
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
      - POSTGRES_USER=${POSTGRES_USER:-n8n_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n_password}
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    extra_hosts:
      - 'dockernet:host-gateway'
      - 'newway:host-gateway'
  n8n_redis:
    container_name: n8n_redis
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - ./data/redis:/data
    extra_hosts:
      - 'dockernet:host-gateway'
      - 'newway:host-gateway'
